#!/usr/bin/env bash

cargo build --release
if [ $? -ne 0 ]; then
    echo "Build failed, aborting."
    exit 1
fi

rm -rf examples
cp -r ../unisamples/scaled examples

rm -rf results
mkdir -p results

for a in examples/* ; do
    for b in examples/* ; do
        if [ "x$a" = "x$b" ] ; then continue ; fi
        ba=`basename $a`
        bb=`basename $b`
        for m in I U X D ; do
            fn=${ba}_${bb}_${m}
            echo $fn
            target/release/rust-geo-booleanop-experiment $a $b -${m,,} >results/${fn}
        done
    done
done

find ./results -type f -size 0 -delete

