#!/usr/bin/env bash

par=15
width=100
height=100

rm -rf ../pngs
mkdir -p ../pngs
for r in ../svgs/* ; do
    while [ "`jobs -r | wc -l`" = "${1:-$par}" ] ; do sleep .01 ; done
    br=`basename ${r%.svg}`
    echo $br
    inkscape --export-filename ../pngs/${br}.png -w ${2:-$width} -h ${3:-$height} -y 0 $r &
done

wait

